authsysproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

users/backup/backup3923/urls.py
from django.urls import re_path as url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^button', views.button),
    url(r'^$', views.base1),
    url(r'^external', views.external),
    url(r'^index', views.index),
    url(r'^logout', views.logout),
    url(r'^hyper', views.hyper),
    url(r'^register', views.register),
]

users/backup/urls.py
from django.urls import re_path as url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.button),
    # url(r'^output', views.output, name="script"),
    url(r'^external', views.external),
    url(r'^index', views.index),
    url(r'^buttonresult', views.buttonresult),
    # url(r'^my_view', views.my_view),
]

users/urls.py
from django.urls import re_path as url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^button', views.button),
    url(r'^$', views.base1),
    url(r'^external', views.external),
    url(r'^logout', views.logout),
    url(r'^hyper', views.hyper),
    # url(r'^index', views.index),
    url(r'^register', views.register),
]

users/models.py
from django.db import models

# Create your models here.

users/backup/backup3923/forms.py
from django import forms

class RadioForm(forms.Form):
    options = (
        ('Yes', 'Yes'),
        ('No', 'No')
    )

    radio_choice = forms.ChoiceField(
        choices=options,
        widget=forms.RadioSelect
    )

users/backup/forms.py
from django import forms

class RadioForm(forms.Form):
    options = (
        ('Yes', 'Yes'),
        ('No', 'No')
    )

    radio_choice = forms.ChoiceField(
        choices=options,
        widget=forms.RadioSelect
    )

users/forms.py
from django import forms

class RadioForm(forms.Form):
    options = (
        ('Yes', 'Yes'),
        ('No', 'No')
    )

    radio_choice = forms.ChoiceField(
        choices=options,
        widget=forms.RadioSelect
    )

users/backup/backup3923/views.py
from django.shortcuts import render
import sys
from . forms import RadioForm

from msrest.authentication import CognitiveServicesCredentials
from azure.cognitiveservices.personalizer import PersonalizerClient
from azure.cognitiveservices.personalizer.models import RankableAction,RankedAction ,RewardRequest, RankRequest
import pandas as pd
import csv
import datetime
import requests
import pyodbc
import webbrowser

def base1(request):
    return render(request, 'base.html')

def button(request):
    return render(request, 'home.html')

def logout(request):
    return render(request, 'logout.html')

def register(request):
    return render(request, 'register.html')

def executeQuery(url, ontology, token, query):
    if not url.endswith("/"):
       url += "/"
    post_data = {'ontology_name': ontology, 'query': query}
    headers = {'Content-Type': 'application/json', 'x-api-key': token}
    response = requests.post(url + "timbr/api/query/", headers = headers, json = post_data, verify = False)
    response_data = response.json()
    if response_data['status'] == 'success':
        df = pd.DataFrame(response_data['data'])
        return df
    else:
        raise Exception("Error in request: " + response_data['data'])

def timbrcall():
    url = "https://cap-env.timbr.ai" # http://<hostname> or https://<hostname>
    ontology = "personalizerpoc" # ontology name
    token = "tk_fee921d10dbb8127b750959f97ab9be5262380f57845e4fa10f14a75e750a978" # user token
    query = """SELECT DISTINCT 
        `account_id` AS `Account_ID`, 
        `cards_account_id[cards].type_of_card` AS `Card_Assigned`,
        `annual_income` AS `Annual_Income`,  
        `~zipcode[zipcode].per_capita_income_zipcode` AS `Avg_Income_In_Zip`,
        `birth_year` AS `Birth_Year`, 
        `bussiness_owner` AS `Bus_Owner`, 
        `current_age` as `Current_Age`, 
        `existing_customer` AS `Customer_Ind`, 
        `fico_score` AS `Credit_Scope`, 
        `gender` AS `Gender`, 
        `highnetworth` AS `HNI_Customer`, 
        `home_owner` AS `Home_Owner`, 
        `incarcinated` AS `Incarcerated`, 
        `last_time_when_card_was_purchased` AS `Last_Card_Opened`, 
        `~account_id[logins].login_duration` AS `Login_Duration`, 
        `~account_id[logins].login_time` AS `Login_Time`, 
        `num_credit_cards` AS `Num_Cards`, 
        `retirement_age` AS `Retirement_Age`, 
        `total_debt` AS `Total_Debt`, 
        `zipcode` AS `Zipcode` 
    FROM `dtimbr`.`customer`
    where 
    --account_id ='708082087' AND
    `cards_account_id[cards].type_of_card`<>'None'
    --LIMIT 10"""

    response = executeQuery(url, ontology, token, query)
    print(response)
    response=response.dropna(subset='Card_Assigned')
    #response=response[response['Card_Assigned']!='None']
    #print(response['Card_Assigned'].unique())
    return response

# get actions and their features

def get_actions(actions_and_features):
    res = []
    for action_id, feat in actions_and_features.items():
        action = RankableAction(id=action_id, features=[feat])
        res.append(action)
    return res

# Context of the user to which the action must be presented.
# Function to convert a Timbr to list of dictionary object

def timbrdf_to_dict_obj(timbrdf):
    # formatting the data
    # currency to float
    timbrdf['Annual_Income'] = timbrdf['Annual_Income'].str.replace('$', '').str.replace(',', '')
    timbrdf['Annual_Income'] = timbrdf['Annual_Income'] .astype(float)
    timbrdf['Avg_Income_In_Zip'] = timbrdf['Avg_Income_In_Zip'].str.replace('$', '').str.replace(',', '')
    timbrdf['Avg_Income_In_Zip'] = timbrdf['Avg_Income_In_Zip'].astype(float)
    timbrdf['Total_Debt'] = timbrdf['Total_Debt'].str.replace('$', '').str.replace(',', '')
    timbrdf['Total_Debt'] = timbrdf['Total_Debt'].astype(float)
    # year to int
    timbrdf['Birth_Year'] = timbrdf['Birth_Year'].str.strip()
    timbrdf['Birth_Year'] = timbrdf['Birth_Year'].astype(int)
    # removing white spaces and making uniform string
    timbrdf['Bus_Owner'] = timbrdf['Bus_Owner'].str.strip()
    timbrdf['Bus_Owner'] = timbrdf['Bus_Owner'].str.title()
    timbrdf['Customer_Ind'] = timbrdf['Customer_Ind'].str.strip()
    timbrdf['Customer_Ind'] = timbrdf['Customer_Ind'].str.title()
    timbrdf['HNI_Customer'] = timbrdf['HNI_Customer'].str.strip()
    timbrdf['HNI_Customer'] = timbrdf['HNI_Customer'].str.title()
    timbrdf['Home_Owner'] = timbrdf['Home_Owner'].str.strip()
    timbrdf['Home_Owner'] = timbrdf['Home_Owner'].str.title()
    timbrdf['Incarcerated'] = timbrdf['Incarcerated'].str.strip()
    timbrdf['Incarcerated'] = timbrdf['Incarcerated'].str.title()
    timbrdf['Incarcerated'] = timbrdf['Incarcerated'].str.strip()
    timbrdf['Incarcerated'] = timbrdf['Incarcerated'].str.title()

    timbrdf['context_features'] = timbrdf.iloc[:,2:].to_dict('records')
    data = timbrdf[['Account_ID','Card_Assigned','context_features']].to_dict(orient='records')
    return data

def external(request):
    global acct_id, user_data, Account_ID, Card_Assigned, Annual_Income, Birth_Year, Zipcode
    if request.method == "POST":
        acct_id = request.POST.get('param')
        pass_id = request.POST.get('param1')
        print(acct_id)
        print(pass_id)

        if pass_id == 'capgemini':
            print('login successful')
            # extract the data from Timbr.
            timbrdf = timbrcall()
            timbrdf1 = timbrdf.loc[timbrdf['Account_ID'] == acct_id]
            # print(timbrdf1)
            user_data = timbrdf_to_dict_obj(timbrdf1)
            print(user_data)

            for i in user_data:
                Account_ID = (i['Account_ID'])
                Card_Assigned = (i['Card_Assigned'])
                Annual_Income = (i['context_features']['Annual_Income'])
                Birth_Year = (i['context_features']['Birth_Year'])
                Zipcode = (i['context_features']['Zipcode'])
                break

            return render(request, "home1.html", {'data1': Account_ID, 'data2': Birth_Year, 'data3': Card_Assigned,
                                              'data4': Zipcode, 'data5': Annual_Income})
        else:
            out1 = "Incorrect ID or Password"
            print(out1)
            return render(request, "home.html",{'dataout': out1})

    return render(request, "home1.html", {'data1': Account_ID, 'data2': Birth_Year, 'data3': Card_Assigned,
                                          'data4': Zipcode, 'data5': Annual_Income})


def index(request):
    global actionid, account_id, filenames, eventid, actual_card, prob_list, client
    # Instantiate a Personalizer client
    endpoint = "https://hyperpersonalizerpoc.cognitiveservices.azure.com/"
    key = "bc343f1d5e22457994f787ddfdb6a1db"
    client = PersonalizerClient(endpoint, CognitiveServicesCredentials(key))

    # The list of actions to be ranked with metadata associated for each action.
    actions_and_features = {
        "Rewards card": {
            "Annual_Income": 60000 - 99000,
            "Home_Owner": "No"
        },
        "Business Card": {
            "Bus_Owner": "Yes",
            "HNI_Customer": "No"
        },
        "Business Premium": {
            "Bus_Owner": "Yes",
            "HNI_Customer": "Yes"
        },
        "Luxury Card": {
            "Bus_Owner": "No",
            "HNI_Customer": "Yes",
            "Home_Owner": "Yes"
        },
        "Platinum Card": {
            "Bus_Owner": "No",
            "HNI_Customer": "Yes",
            "Home_Owner": "No"
        },
        "Student Card": {
            "Current_Age": 18 - 21,
            "Annual_Income": "0-30000"
        }
    }
    actions = get_actions(actions_and_features)

    if request.method == "POST":
        print(user_data)

    def rank_call(actions, context):
        rank_request = RankRequest(actions=actions, context_features=[context])
        try:
            rank_response = client.rank(rank_request=rank_request)
            return rank_response
        except Exception as e:
            print(e.message)

    for data in user_data:
        account_id = data['Account_ID']
        context = data["context_features"]
        print("Account id: " + str(account_id))
        print("*" * 15 + "Sending Rank Event" + "*" * 15)
        rank_response = rank_call(actions, context)
        if not rank_response:
            # rank call is failing
            break
        print("Rank API response:")
        prob_list = [{i.id: i.probability} for i in rank_response.ranking]
        print(prob_list)
        eventid = rank_response.event_id
        actionid = rank_response.reward_action_id
        print("Rank Response event_id is : " + eventid)
        print("recommended card is : " + actionid)
        actual_card = data["Card_Assigned"]
        print(data)

    return render(request, 'new.html', {'data1':Account_ID, 'data2':Birth_Year, 'data3':Card_Assigned,
                                         'data4':Zipcode, 'data5':Annual_Income, 'data6':actionid})


def hyper(request):
    global reward_score, eventid, reward_data, user_data, users_reward_data, current_time

    def reward_call(eventid, reward_score):
        # rank_request = RankRequest(actions=actions, context_features=[context])
        try:
            client.events.reward(event_id=eventid, value=reward_score)
        except Exception as e:
            print(e.message)

    if request.method == 'POST':
        form = RadioForm(request.POST)
        if form.is_valid():
            selected_choice = form.cleaned_data['radio_choice']
            print(selected_choice)

            if selected_choice == 'Yes':
                reward_score = 1.0
                print('yes button pressed')
                print(reward_score)
            elif selected_choice == 'No':
                reward_score = 0.0
                print('no button pressed')
                print(reward_score)
            print(eventid)

users/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <title>Dynamic Personalizer</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Css Style -->
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">

  </head>

   <style>
body {
  background-color: #E6E6FA;
}
</style>

  <body id="bg">
  {% load static %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="main-navbar">
        <div class="container">
          <form action="/button/" method="post">
              {% csrf_token %}
              <a href="http://127.0.0.1:8000" style="color: white; background-color: #fd5e14;"> <h5>Home</h5>
              </a>
          </form>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

          &nbsp; &nbsp; &nbsp;
            <form action="/register/" method="post">
              {% csrf_token %}
                <input type="submit" value="New User" style="color: white; background-color: #fd5e14;"> <br>
            </form>

            &nbsp; &nbsp; &nbsp;
            <form action="/button/" method="post">
              {% csrf_token %}
                <input type="submit" value="Existing User" style="color: white; background-color: #fd5e14;"> <br>
            </form>
          </div>
          <form action="/button/" method="post">
              {% csrf_token %}
              <a href="http://127.0.0.1:8000">
                <img src="{% static 'images/capgemini.png' %}" height="30" width="156" />
              </a>
          </form>
        </div>
    </nav>

      <div>
        <div class="container">

          Explore our latest thought leadership, ideas, and insights on the issues that are shaping the future of business and society.

        </div>
        {% block content %}
        {% endblock content %}
      </div>

      <!-- Optional JavaScript; choose one of the two! -->

      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <!--
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
      -->
  </body>
</html>

users/templates/login.html
<!--{% extends 'users/base.html' %}-->
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}">
    <div class="container" style="margin-top: 30px;">
    <form action="/login/" method="POST">
      {% csrf_token %}
        {% csrf_token %}
        Enter Account ID:
        <input type="text" name="param" required><br><br>
        <input type="submit" value="Submit">

  <div class="row">
    <div class="col">
      <input type="text" class="form-control" placeholder="First name">
    </div>
    <div class="col">
      <input type="text" class="form-control" placeholder="Last name">
    </div>
  </div>
   <div class="row">
    <div class="col">
      <input type="text" class="form-control" placeholder="First1 name">
    </div>
    <div class="col">
      <input type="text" class="form-control" placeholder="Last1 name">
    </div>
  </div>

</form>
    </div>
{% endblock %}</title>

users/templates/new.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


<head>
<title>Dynamic Personalizer</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}

/* Style the header */
header {
  background-color: black;
  color: white;
  width: 100%;
  height:75px;
}

/* Create two columns/boxes that floats next to each other */
nav {
  float: left;
  width: 70%;
  height: 550px; /* only for demonstration, should be removed */
  background: #D1D1F6;
  padding: 20px;
<!--  background-image: url(../static/images/capgemini.jfif);-->
  background-repeat : no-repeat;
  background-blend-mode: light;
  background-width: 20%

  padding: 200px;

<!--  background-size: cover;-->

}

article {
  float: left;
  padding: 20px;
  width: 30%;
  background-color: #E6E6FA;
  height: 550px; /* only for demonstration, should be removed */
}

/* Clear floats after the columns */
section::after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
footer {
  background-color: #777;
  padding: 10px;
  text-align: center;
  color: white;
}

/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
@media (max-width: 600px) {
  nav, article {
    width: 50%;
    height: auto;
  }

}
</style>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>

<body>
<header>
<h7>
        <div class="w3-container">

            <div class="row">
                <div class="col-sm-1">

                </div>
            </div> <br>
            <div class="row">
                <div class="col-sm-1">
                  <form action="/button/" method="post">
                      {% csrf_token %}
                      <a href="http://127.0.0.1:8000/" style="color: white; background-color: #fd5e14;"> <h5>Home</h5>
                      </a>
                  </form>
                </div>

                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <div class="col-sm-1">
                    <form action="/button/" method="post">
                      {% csrf_token %}
                      <a href="http://127.0.0.1:8000/">
                        <img src="{% static 'images/capgemini.png' %}" height="30" >
                      </a>
                    </form>
                </div>

                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                <div class="col-sm-1">
                    <form action="/logout/" method="post">
                      {% csrf_token %}
                        <input type="submit" value="Sign out" style="color: white; background-color: #fd5e14; text-align:right"> <br>
                    </form>
                </div>
            </div>
        </div>
</h7>
</header>

<section>
  <nav>
    <h7><i><b style="color:blue">Welcome </b> <b>{{data10}} </b></i></h7> <br>

    <form action="/external/" method="post">
        {% csrf_token %}
    </form>
    <br>

        <div class="w3-container">

          <div class="w3-bar w3-black">
            <button class="w3-bar-item w3-button tablink w3-red" onclick="openCity(event,'Account')">Account</button>
            <button class="w3-bar-item w3-button tablink" onclick="openCity(event,'Profile')">Profile</button>
            <button class="w3-bar-item w3-button tablink" onclick="openCity(event,'Travel')">Travel</button>
            <button class="w3-bar-item w3-button tablink" onclick="openCity(event,'Reward')">Reward Information</button>

          </div>



          <div id="Account" class="w3-container w3-border city">
                <div class="container">
                    <div class="row">
                        <div class="row">
                            <div class="col-sm-4">
                            </div>
                        </div> <br>



                        <div class="col-sm-4">
                            <b style="color:blue">Account ID: </b> {{data1}}
                        </div>
                        <div class="col-sm-4">
                           <b style="color:blue"> Card Assigned: </b>{{data3}}
                        </div>
                    </div> <br>
                    <div class="row">
                        <div class="col-sm-4">
                            <b style="color:blue">Home_Owner:</b> {{data8}}
                        </div>
                        <div class="col-sm-4">
                           <b style="color:blue">Bus_Owner: </b>{{data9}}
                        </div>
                        <div class="col-sm-4">
                            <b style="color:blue">Annual Income:</b> {{data5}}
                        </div>
                    </div>
                </div>
          </div>

          <div id="Profile" class="w3-container w3-border city" style="display:none">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">

                    </div>
                </div> <br>
                <div class="row">
                    <br>
                    <div class="col-sm-4">
                        <b style="color:blue">Birth Year:</b> {{data2}}
                    </div>
                    <div class="col-sm-4">
                        <b style="color:blue">Age: </b>{{data15}}
                    </div>
                </div> <br>
                <div class="row">
                        <div class="col-sm-4">
                            <b style="color:blue">Address: </b>{{data11}}
                        </div>
                        <div class="col-sm-4">
                            <b style="color:blue">Apartment: </b>{{data12}}
                        </div>
                        <div class="col-sm-4">
                            <b style="color:blue">City: </b>{{data13}}
                        </div>
                    </div> <br>
                    <div class="row">
                        <div class="col-sm-4">
                            <b style="color:blue">State: </b>{{data14}}
                        </div>
                        <div class="col-sm-4">
                           <b style="color:blue">Zipcode: </b>{{data4}}
                        </div>
                    </div> <br>
                    <div class="row">
                    <br>
                    <div class="col-sm-4">
                        <b style="color:blue">Phone:</b> {{data16}}
                    </div>
                    <div class="col-sm-4">
                        <b style="color:blue">Email: </b>{{data17}}
                    </div>
                </div> <br>
            </div>
          </div>

              <div id="Travel" class="w3-container w3-border city" style="display:none">
                </div>

             <div id="reward" class="w3-container w3-border city" style="display:none">
                </div>

        </div>

        <script>
        function openCity(evt, cityName) {
          var i, x, tablinks;
          x = document.getElementsByClassName("city");
          for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
          }
          tablinks = document.getElementsByClassName("tablink");
          for (i = 0; i < x.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
          }
          document.getElementById(cityName).style.display = "block";
          evt.currentTarget.className += " w3-red";
        }
        </script>
  </nav>

    <article>
        <h5 align="center"> Dear {{data10}}, based on your financial profile and few other individual characteristics, we are pleased to present you this pre-approved card  </h5>
            <h6 align="center"><b style="color:blue"><i>{{data6}} </i></b></h6> <br>

        <p style="text-align:center;"><img src="{% get_static_prefix %}images/{{ data6 }}.png" alt="" height="100"><br><br>

          <form action = "/hyper/" method="POST">
           {% csrf_token %}
           <div class="w3-center" style="text-align:center">

            <p> <b>Did you like the suggested Credit Card? </b></p>
                <div id="id_radio_choice">
                    <label for="id_radio_choice_0"><input type="radio" name = "radio_choice" value="Yes" required id="id_radio_choice_0"
                                                          style="text-align:center" > Apply <i class="glyphicon glyphicon-thumbs-up" style="font-size:24px;color:blue;"></i> </label><br>
                    <label for="id_radio_choice_1"><input type="radio" name = "radio_choice" value="No" required id="id_radio_choice_1"
                                                          style="text-align:center" > Decline <i class="glyphicon glyphicon-thumbs-down" style="font-size:24px;color:red;"></i> </label><br>
                    <button type="submit" style="color: white; background-color: #fd5e14;">Submit!</button>
                </div>
           </div>
          </form>

    </article>
</section>
</body>
</html>